# Generated by Django 3.1.5 on 2021-01-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nama',
        ),
        migrations.AddField(
            model_name='post',
            name='jumlahart',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AddField(
            model_name='post',
            name='namakk',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='nomorhp',
            field=models.CharField(default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='alamat',
            field=models.CharField(default='-', max_length=200),
        ),
    ]
