# Generated by Django 3.1.5 on 2021-01-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdata', '0002_auto_20210119_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='alamat',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='namakk',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='nomorhp',
            field=models.CharField(default='', max_length=10),
        ),
    ]
