# Generated by Django 3.1.5 on 2021-01-19 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputdata', '0003_auto_20210119_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nomorhp',
            field=models.CharField(default='', max_length=15),
        ),
    ]
